import 'controller/create_wallet_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class CreateWalletScreen extends GetWidget<CreateWalletController> {const CreateWalletScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 17.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 19.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 3.v, bottom: 1.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_create_wallet".tr, margin: EdgeInsets.only(left: 35.h)))])), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 351.h, margin: EdgeInsets.only(right: 38.h), child: Text("msg_create_a_wallet".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 1.38))), SizedBox(height: 32.v), Text("lbl_name".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomTextFormField(controller: controller.nameController, hintText: "lbl_auto_filled".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1), SizedBox(height: 19.v), Text("lbl_wallet_id".tr, style: theme.textTheme.titleMedium), SizedBox(height: 15.v), CustomTextFormField(controller: controller.autogeneratedvaController, hintText: "lbl_auto_generated".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done), SizedBox(height: 5.v)]))])), bottomNavigationBar: CustomElevatedButton(text: "lbl_create_wallet".tr, margin: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 30.v), onTap: () {onTapCreatewallet();}))); } 
/// Navigates to the walletScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the walletScreen.
onTapCreatewallet() { Get.toNamed(AppRoutes.walletScreen, ); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
