import 'controller/success_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class SuccessScreen extends GetWidget<SuccessController> {const SuccessScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 83.v, leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 40.v, bottom: 19.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_checkout".tr, margin: EdgeInsets.only(left: 35.h)), styleType: Style.bgFill), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 20.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 17.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 5.h, top: 4.v, bottom: 2.v), child: Text("lbl_shipping".tr, style: theme.textTheme.titleSmall)), Padding(padding: EdgeInsets.only(top: 12.v, bottom: 11.v), child: SizedBox(width: 35.h, child: Divider(color: appTheme.gray400, indent: 15.h))), CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 15.h)), Padding(padding: EdgeInsets.only(left: 5.h, top: 5.v), child: Text("lbl_payment".tr, style: theme.textTheme.titleSmall)), Padding(padding: EdgeInsets.only(top: 12.v, bottom: 11.v), child: SizedBox(width: 35.h, child: Divider(color: appTheme.gray400, indent: 15.h))), CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 15.h)), Padding(padding: EdgeInsets.only(left: 5.h, top: 3.v, bottom: 3.v), child: Text("lbl_review".tr, style: theme.textTheme.titleSmall))])), Spacer(), Container(decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(svgPath: ImageConstant.imgTeenyiconstickcirclesolid, height: 40.adaptSize, width: 40.adaptSize), SizedBox(height: 16.v), Text("lbl_successful2".tr, style: CustomTextStyles.headlineSmallSemiBold), Container(width: 359.h, margin: EdgeInsets.only(left: 14.h, top: 21.v, right: 15.h), child: Text("msg_your_payment_has".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71))), SizedBox(height: 50.v), CustomElevatedButton(height: 52.v, text: "lbl_go_back_home".tr, onTap: () {onTapGobackhome();})]))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
/// Navigates to the pharmacyScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the pharmacyScreen.
onTapGobackhome() { Get.toNamed(AppRoutes.pharmacyScreen, ); } 
 }
