import '../notifications_screen/widgets/listappointment_item_widget.dart';import 'controller/notifications_controller.dart';import 'models/listappointment_item_model.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';class NotificationsScreen extends GetWidget<NotificationsController> {const NotificationsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 17.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 19.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 3.v, bottom: 1.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_notifications".tr, margin: EdgeInsets.only(left: 35.h)))])), Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 19.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 18.v), Text("lbl_new_1".tr.toUpperCase(), style: CustomTextStyles.labelLargeSemiBold), SizedBox(height: 14.v), Expanded(child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 50.v);}, itemCount: controller.notificationsModelObj.value.listappointmentItemList.value.length, itemBuilder: (context, index) {ListappointmentItemModel model = controller.notificationsModelObj.value.listappointmentItemList.value[index]; return ListappointmentItemWidget(model);}))), Text("lbl_earlier".tr.toUpperCase(), style: CustomTextStyles.labelLargeBluegray40001), SizedBox(height: 631.v), Container(padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 4.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 23.v), SizedBox(width: 383.h, child: Text("msg_your_appointment2".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray90001.copyWith(height: 1.43)))]))]))))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
