import 'controller/create_story_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class CreateStoryScreen extends GetWidget<CreateStoryController> {const CreateStoryScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 13.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 26.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, bottom: 5.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_create_story".tr, margin: EdgeInsets.only(left: 35.h)))])), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_title".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), CustomTextFormField(controller: controller.enterController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1), SizedBox(height: 20.v), Container(decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_story".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 15.v), CustomTextFormField(controller: controller.checkmarkController, hintText: "lbl_enter_text".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), child: CustomImageView(svgPath: ImageConstant.imgCheckmark)), suffixConstraints: BoxConstraints(maxHeight: 128.v), maxLines: 7, contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 9.v)), SizedBox(height: 6.v), Align(alignment: Alignment.centerRight, child: Text("lbl_0_1000".tr, style: CustomTextStyles.labelLargeIndigo100)), SizedBox(height: 22.v), Container(padding: EdgeInsets.symmetric(vertical: 1.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_photos".tr, style: CustomTextStyles.titleMediumBluegray900_1)), SizedBox(height: 17.v), CustomImageView(svgPath: ImageConstant.imgFrame12564, height: 100.v, width: 384.h), SizedBox(height: 5.v)]))])), bottomNavigationBar: CustomElevatedButton(text: "lbl_publish".tr, margin: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 31.v), onTap: () {onTapPublish();}))); } 
/// Navigates to the scwCommunityScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the scwCommunityScreen.
onTapPublish() { Get.toNamed(AppRoutes.scwCommunityScreen, ); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
