import 'controller/reschedule_appointment_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image_1.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_2.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class RescheduleAppointmentScreen extends GetWidget<RescheduleAppointmentController> {const RescheduleAppointmentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer.withOpacity(1), appBar: CustomAppBar(height: 65.v, title: AppbarSubtitle2(text: "msg_reschedule_appointment".tr, margin: EdgeInsets.only(left: 20.h)), actions: [AppbarImage1(svgPath: ImageConstant.imgEvacloseoutlineBlack900, margin: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 351.h, margin: EdgeInsets.only(left: 2.h, right: 38.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_this_appointment2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "msg_september_12_2022".tr, style: CustomTextStyles.titleSmallBlueA400_1)]), textAlign: TextAlign.left)), CustomElevatedButton(height: 43.v, text: "lbl_yes".tr, margin: EdgeInsets.only(left: 2.h, top: 22.v), onTap: () {onTapYes();}), CustomOutlinedButton(text: "lbl_no".tr, margin: EdgeInsets.only(left: 2.h, top: 20.v, bottom: 8.v))])))); } 
/// Navigates to the rescheduleAppointmentOneScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the rescheduleAppointmentOneScreen.
onTapYes() { Get.toNamed(AppRoutes.rescheduleAppointmentOneScreen, ); } 
 }
