import 'controller/rate_doctor_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';import 'package:medtech/widgets/custom_rating_bar.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class RateDoctorScreen extends GetWidget<RateDoctorController> {const RateDoctorScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 21.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 2.v, bottom: 2.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_rate_doctor".tr, margin: EdgeInsets.only(left: 35.h)))])), Expanded(child: Container(padding: EdgeInsets.symmetric(vertical: 20.v), child: Column(children: [SizedBox(height: 5.v), CustomImageView(imagePath: ImageConstant.imgEllipse5165x165, height: 165.adaptSize, width: 165.adaptSize, radius: BorderRadius.circular(82.h)), SizedBox(height: 23.v), Text("msg_dr_rashida_mohammed3".tr, style: CustomTextStyles.titleLargeMedium), SizedBox(height: 8.v), Text("lbl_haematologist".tr, style: CustomTextStyles.bodyLargeBluegray500), SizedBox(height: 23.v), CustomRatingBar(initialRating: 0, itemSize: 24, itemCount: 5), SizedBox(height: 35.v), Container(padding: EdgeInsets.symmetric(vertical: 1.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_leave_a_comment".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.commentController, margin: EdgeInsets.only(left: 19.h, top: 15.v, right: 19.h), hintText: "lbl_enter_text".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), child: CustomImageView(svgPath: ImageConstant.imgCheckmark)), suffixConstraints: BoxConstraints(maxHeight: 128.v), maxLines: 7, contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 9.v)), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(top: 6.v, right: 19.h), child: Text("lbl_0_200".tr, style: CustomTextStyles.labelLargeIndigo100))), Spacer(), CustomElevatedButton(height: 43.v, text: "lbl_submit".tr, margin: EdgeInsets.symmetric(horizontal: 19.h)), CustomOutlinedButton(text: "lbl_cancel".tr, margin: EdgeInsets.only(left: 19.h, top: 20.v, right: 19.h))])))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
