import 'controller/view_patient_three_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/presentation/view_patient_one_page/view_patient_one_page.dart';import 'package:medtech/presentation/view_patient_three_page/view_patient_three_page.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';class ViewPatientThreeTabContainerScreen extends GetWidget<ViewPatientThreeTabContainerController> {const ViewPatientThreeTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 20.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 2.v, bottom: 2.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_view_patient".tr, margin: EdgeInsets.only(left: 35.h)))])), SizedBox(height: 30.v), Expanded(child: SingleChildScrollView(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 19.h, right: 87.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse87, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h)), Expanded(child: Padding(padding: EdgeInsets.only(left: 15.h, top: 5.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ejiro_osarobo".tr, style: CustomTextStyles.headlineSmallSemiBold), SizedBox(height: 5.v), Row(children: [Text("lbl_gender_female".tr, style: CustomTextStyles.bodyMediumGray600_1), Padding(padding: EdgeInsets.only(top: 2.v), child: SizedBox(child: Divider(color: appTheme.gray600, indent: 15.h))), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("lbl_dob_12_12_1993".tr, style: CustomTextStyles.bodyMediumGray600_1))])])))])), SizedBox(height: 38.v), Container(height: 26.v, width: 389.h, child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.gray900, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Work Sans', fontWeight: FontWeight.w600), unselectedLabelColor: appTheme.blueGray500, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Work Sans', fontWeight: FontWeight.w400), indicatorColor: theme.colorScheme.primary, tabs: [Tab(child: Text("lbl_overview".tr)), Tab(child: Text("msg_conditions_allergies".tr)), Tab(child: Text("lbl_medication".tr)), Tab(child: Text("lbl_history".tr))])), SizedBox(height: 654.v, child: TabBarView(controller: controller.tabviewController, children: [ViewPatientOnePage(), ViewPatientThreePage(), ViewPatientThreePage(), ViewPatientThreePage()]))])))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
