import 'controller/specialty_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class SpecialtyScreen extends GetWidget<SpecialtyController> {const SpecialtyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer.withOpacity(1), body: Container(width: 390.h, padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 10.v), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 13.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("msg_medical_officers".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 4.v), Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 13.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("msg_consultant_pediatrician".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 4.v), Container(padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 12.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Text("msg_consultant_family".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 4.v), CustomElevatedButton(height: 44.v, text: "msg_consultant_haematologist".tr, buttonStyle: CustomButtonStyles.fillPrimaryContainerTL22, buttonTextStyle: theme.textTheme.bodyMedium!, onTap: () {onTapConsultant();})])))); } 
/// Navigates to the bookAppointmentNowOneScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the bookAppointmentNowOneScreen.
onTapConsultant() { Get.toNamed(AppRoutes.bookAppointmentNowOneScreen, ); } 
 }
