import 'controller/view_request_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_circleimage.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_3.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_7.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class ViewRequestScreen extends GetWidget<ViewRequestController> {const ViewRequestScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(height: 103.v, leadingWidth: 85.h, leading: AppbarCircleimage(imagePath: ImageConstant.imgEllipse565x651, margin: EdgeInsets.only(left: 20.h, bottom: 1.v)), title: Padding(padding: EdgeInsets.only(left: 15.h), child: Column(children: [AppbarSubtitle3(text: "lbl_floyd_miles".tr), AppbarSubtitle7(text: "lbl_30_years_old".tr, margin: EdgeInsets.only(top: 6.v, right: 5.h)), AppbarSubtitle7(text: "lbl_male".tr, margin: EdgeInsets.only(top: 7.v, right: 56.h))]))), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 20.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 1.h, top: 9.v), child: Text("lbl_date_time".tr, style: CustomTextStyles.titleMediumSemiBold_3)), Padding(padding: EdgeInsets.only(left: 1.h, top: 12.v), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_11th_nov_2022".tr, style: CustomTextStyles.titleSmallBlueA400SemiBold), TextSpan(text: "lbl3".tr, style: CustomTextStyles.titleSmallIndigo100), TextSpan(text: "lbl_10_00_am2".tr, style: CustomTextStyles.titleSmallBlueA400SemiBold)]), textAlign: TextAlign.left)), Padding(padding: EdgeInsets.only(left: 1.h, top: 31.v), child: Text("lbl_note".tr, style: CustomTextStyles.titleMediumSemiBold_3)), Container(width: 386.h, margin: EdgeInsets.only(left: 1.h, top: 11.v), child: Text("msg_lorem_ipsum_dolor12".tr, maxLines: 11, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.50))), SizedBox(height: 29.v), CustomElevatedButton(height: 43.v, text: "lbl_accept".tr), SizedBox(height: 20.v), CustomOutlinedButton(text: "lbl_reject".tr, onTap: () {onTapReject();})])))); } 
/// Navigates to the rejectAppointmentScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the rejectAppointmentScreen.
onTapReject() { Get.toNamed(AppRoutes.rejectAppointmentScreen, ); } 
 }
