import 'controller/add_card_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_switch.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class AddCardScreen extends GetWidget<AddCardController> {const AddCardScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 17.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 19.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 3.v, bottom: 1.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_add_card".tr, margin: EdgeInsets.only(left: 35.h)))])), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 17.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_add_card_to_fund".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 30.v), Text("lbl_name_on_card".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), CustomTextFormField(controller: controller.nameController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1), SizedBox(height: 19.v), Text("lbl_card_number".tr, style: theme.textTheme.titleMedium), SizedBox(height: 15.v), CustomTextFormField(controller: controller.cardNumberController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1), SizedBox(height: 20.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_expiry_date".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), CustomTextFormField(width: 190.h, controller: controller.expirydateController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1)])), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_cvv".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomTextFormField(width: 186.h, controller: controller.cvvController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1)])]), SizedBox(height: 19.v), Text("lbl_card_pin".tr, style: theme.textTheme.titleMedium), SizedBox(height: 15.v), CustomTextFormField(controller: controller.enternumberoneController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done), SizedBox(height: 21.v), Row(children: [Text("lbl_save_card".tr, style: CustomTextStyles.titleSmallGray90002), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 8.h), value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))]), SizedBox(height: 5.v)]))])), bottomNavigationBar: CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 30.v), onTap: () {onTapAdd();}))); } 
/// Navigates to the fundWalletScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the fundWalletScreen.
onTapAdd() { Get.toNamed(AppRoutes.fundWalletScreen, ); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
