import 'controller/security_one_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_checkbox_button.dart';import 'package:medtech/widgets/custom_icon_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class SecurityOneScreen extends GetWidget<SecurityOneController> {const SecurityOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 14.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 24.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, bottom: 4.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_security".tr, margin: EdgeInsets.only(left: 35.h)))])), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 21.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_password".tr, style: CustomTextStyles.titleMedium18)), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(7.h), child: CustomImageView(svgPath: ImageConstant.imgIconGray900))]), SizedBox(height: 25.v), Divider(color: appTheme.indigo100), SizedBox(height: 24.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_two_factor_authentication".tr, style: CustomTextStyles.titleMedium18)), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(7.h), child: CustomImageView(svgPath: ImageConstant.imgIconGray900))]), SizedBox(height: 25.v), Divider(color: appTheme.indigo100), SizedBox(height: 24.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_deactivate_account".tr, style: CustomTextStyles.titleMedium18)), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(7.h), child: CustomImageView(svgPath: ImageConstant.imgIconGray900))]), SizedBox(height: 30.v), Text("msg_are_you_sure_you".tr, style: theme.textTheme.bodyMedium), Container(width: 338.h, margin: EdgeInsets.only(top: 20.v, right: 51.h), child: Text("msg_doing_this_will".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71))), Obx(() => CustomCheckboxButton(text: "msg_i_understand_the".tr, isExpandedText: true, value: controller.user.value, margin: EdgeInsets.only(top: 15.v, right: 52.h), onChange: (value) {controller.user.value = value;})), SizedBox(height: 25.v), CustomOutlinedButton(width: 115.h, text: "lbl_confirm".tr), SizedBox(height: 5.v)]))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
