import 'controller/bio_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_title.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_text_form_field.dart';class BioScreen extends GetWidget<BioController> {const BioScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.fillPrimaryContainer, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 20.v), CustomAppBar(leadingWidth: 43.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnprimarycontainer, margin: EdgeInsets.only(left: 19.h, top: 2.v, bottom: 2.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_bio".tr, margin: EdgeInsets.only(left: 35.h)))])), Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 373.h, margin: EdgeInsets.only(right: 16.h), child: Text("msg_write_a_brief_description".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 1.50))), SizedBox(height: 29.v), Container(decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Text("lbl_biography".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 15.v), CustomTextFormField(controller: controller.checkmarkController, hintText: "lbl_enter_text".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), child: CustomImageView(svgPath: ImageConstant.imgCheckmark)), suffixConstraints: BoxConstraints(maxHeight: 128.v), maxLines: 7, contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 9.v)), SizedBox(height: 6.v), Align(alignment: Alignment.centerRight, child: Text("lbl_0_300".tr, style: CustomTextStyles.labelLargeIndigo100)), SizedBox(height: 22.v), Divider(), SizedBox(height: 19.v), Text("lbl_services".tr, style: CustomTextStyles.titleMediumSecondaryContainer_1), SizedBox(height: 21.v), Text("lbl_service_type".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), CustomTextFormField(controller: controller.enterbuttonlabeController, hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done), SizedBox(height: 20.v), Row(children: [CustomImageView(svgPath: ImageConstant.imgPlus, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h, top: 3.v, bottom: 3.v), child: Text("lbl_add_service".tr, style: CustomTextStyles.titleSmallPrimarySemiBold))]), SizedBox(height: 5.v)]))])), bottomNavigationBar: CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 19.h, right: 19.h, bottom: 28.v)))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
