import 'controller/service_option_one_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image_1.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_2.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';import 'package:medtech/widgets/custom_outlined_button.dart';class ServiceOptionOneScreen extends GetWidget<ServiceOptionOneController> {const ServiceOptionOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primaryContainer.withOpacity(1), appBar: CustomAppBar(height: 65.v, title: AppbarSubtitle2(text: "lbl_service_option".tr, margin: EdgeInsets.only(left: 20.h)), actions: [AppbarImage1(svgPath: ImageConstant.imgEvacloseoutlineBlack900, margin: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 12.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_how_would_you_like".tr, style: theme.textTheme.bodyMedium)), Container(margin: EdgeInsets.only(left: 2.h, top: 21.v), decoration: AppDecoration.fillPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [Container(padding: EdgeInsets.symmetric(horizontal: 57.h, vertical: 24.v), decoration: AppDecoration.outlineIndigo100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgBiologistscien, height: 50.adaptSize, width: 50.adaptSize), SizedBox(height: 12.v), Text("msg_home_sample_collection".tr, style: CustomTextStyles.titleMediumSemiBold_3), SizedBox(height: 12.v), SizedBox(width: 273.h, child: Text("msg_a_certified_professional".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.37))), SizedBox(height: 10.v), Text("lbl_check_address".tr, style: CustomTextStyles.labelLargeBlueA400), SizedBox(height: 2.v)])), SizedBox(height: 10.v), Container(padding: EdgeInsets.symmetric(horizontal: 72.h, vertical: 24.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgCar, height: 50.adaptSize, width: 50.adaptSize), SizedBox(height: 12.v), Text("msg_visit_diagnostic".tr, style: CustomTextStyles.titleMediumSemiBold_3), SizedBox(height: 12.v), SizedBox(width: 241.h, child: Text("msg_funbell_diagnostics_121".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.37))), SizedBox(height: 12.v), Text("msg_view_direction_in".tr, style: CustomTextStyles.labelLargeBlueA400)])), SizedBox(height: 2.v)])), CustomElevatedButton(height: 43.v, text: "lbl_pay_31_000".tr, margin: EdgeInsets.only(left: 2.h, top: 20.v), onTap: () {onTapPay31000();}), CustomOutlinedButton(text: "lbl_cancel".tr, margin: EdgeInsets.only(left: 2.h, top: 20.v, bottom: 8.v))])))); } 
/// Navigates to the paymentSuccessfulScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the paymentSuccessfulScreen.
onTapPay31000() { Get.toNamed(AppRoutes.paymentSuccessfulScreen, ); } 
 }
