import 'controller/onboarding_controller.dart';import 'package:flutter/material.dart';import 'package:medtech/core/app_export.dart';import 'package:medtech/widgets/app_bar/appbar_image.dart';import 'package:medtech/widgets/app_bar/appbar_subtitle_4.dart';import 'package:medtech/widgets/app_bar/custom_app_bar.dart';import 'package:medtech/widgets/custom_elevated_button.dart';class OnboardingScreen extends GetWidget<OnboardingController> {const OnboardingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: CustomAppBar(height: 88.v, leadingWidth: double.maxFinite, leading: AppbarImage(imagePath: ImageConstant.imgGenescorlogor, margin: EdgeInsets.only(top: 1.v, right: 366.h, bottom: 1.v)), title: AppbarSubtitle4(text: "lbl_genescor".tr, margin: EdgeInsets.only(left: 38.h))), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, padding: EdgeInsets.only(top: 56.v), decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.03, 0.02), end: Alignment(1, 1), colors: [theme.colorScheme.primary, appTheme.blueA400])), child: SizedBox(width: double.maxFinite, child: Column(children: [Container(width: 326.h, margin: EdgeInsets.only(left: 50.h, top: 29.v, right: 51.h), child: Text("msg_the_online_resource".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.headlineLarge!.copyWith(height: 1.25))), SizedBox(height: 31.v), CustomElevatedButton(height: 48.v, width: 219.h, text: "lbl_get_started".tr, buttonStyle: CustomButtonStyles.fillPrimaryContainerTL10, buttonTextStyle: CustomTextStyles.titleMediumPrimarySemiBold, onTap: () {onTapGetstarted();}), SizedBox(height: 35.v), SizedBox(height: 576.v, width: 426.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(svgPath: ImageConstant.imgGroup5, height: 322.v, width: 324.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 28.v)), CustomImageView(imagePath: ImageConstant.imgDoctorwearing, height: 576.v, width: 426.h, alignment: Alignment.center)]))]))))); } 



onTapGetstarted() { // TODO: implement Actions
 } 
 }
